version: '3.9'

services:

  db:
    image: postgres:15.3-alpine3.18
    container_name: %%project-name%%-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - %%project-name%%-database:/var/lib/postgresql/data
    networks:
      - %%project-name%%

  backend:
    image: ${DOCKER_REGISTRY_HOST}/%%project-name%%-backend:${BRANCH_NAME}
    container_name: %%project-name%%-backend
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=%%project-prod-host%%
      - DATABASE_URL=DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

      - SECRET_KEY=$DJANGO_APP_SECRET_KEY
      - DJANGO_SETTINGS_MODULE=app.settings

      - API_KEY=$BACKEND_API_KEY
      - ADMIN_API_KEY=$BACKEND_ADMIN_API_KEY
      - SENTRY_DSN=$SENTRY_DSN
    command:
      - /bin/bash
      - -c
      - |
        python ./manage.py collectstatic --noinput
        python ./manage.py migrate
        gunicorn --bind :8000 --workers 4 app.wsgi:application
    volumes:
      - ./%%project-name%%-backend/app:/code
    depends_on:
      - db
    networks:
      - %%project-name%%


  frontend:
    image: %%project-name%%-frontend
    build: ./%%project-name%%-frontend
    container_name: %%project-name%%-frontend
    environment:
      VITE_JSON_API_BASE_URL: http://localhost:8000/
      VITE_APP_API_BASE_URL: http://localhost:8000
      VITE_API_KEY: k9M3ghBpyFU8DszpfnsrVz3ASTsRESYP
      BASE_URL: /
    volumes:
      - ./%%project-name%%-frontend:/app/src
    ports:
      - "3000:3000"
    networks:
      - %%project-name%%
    #command: bash -c "while true; do sleep 2; done"

networks:
  %%project-name%%:
